defmodule HexEmpire.Golden do
  @moduledoc """
  Shared helpers for the golden-trace differential tests.

  Loads the JSONL traces produced by the original JS engine (`test/golden/`,
  generated by `harness/`) and snapshots the Elixir game state in the exact
  shape the traces record — the snapshot shape must stay byte-identical to
  keep the golden comparisons working.
  """

  @golden Path.expand("../golden", __DIR__)

  @doc "All decoded lines of `test/golden/trace_<suffix>.jsonl`."
  def trace(suffix) do
    @golden
    |> Path.join("trace_#{suffix}.jsonl")
    |> File.stream!()
    |> Enum.map(&Jason.decode!/1)
  end

  @doc "The first (init) line of a seed's trace."
  def init_line(seed), do: hd(trace(seed))

  @doc "Per-party army snapshots in the trace's shape (sorted by id)."
  def army_snapshot(game) do
    for party <- 0..3 do
      game.armies_by_party
      |> Enum.at(party)
      |> Enum.map(fn id ->
        key = Map.fetch!(game.army_pos, id)
        a = Map.fetch!(game.fields, key).army

        %{
          "id" => a.id,
          "f" => key,
          "c" => a.count,
          "m" => a.morale,
          "moved" => if(a.moved, do: 1, else: 0)
        }
      end)
      |> Enum.sort_by(& &1["id"])
    end
  end

  @doc "Every field's type/estate/party in board order, in the trace's shape."
  def field_snapshot(game) do
    for key <- game.field_order do
      f = Map.fetch!(game.fields, key)

      %{
        "k" => key,
        "t" => Atom.to_string(f.type),
        "e" => if(f.estate, do: Atom.to_string(f.estate), else: nil),
        "p" => f.party
      }
    end
  end
end
