defmodule HexEmpire.Engine.CityNames do
  @moduledoc "Exact CITY_NAMES list from original/cityNames.js (order matters for RNG-driven naming)."

  @names [
    "Abu Dhabi",
    "Abuja",
    "Accra",
    "Addis Ababa",
    "Algiers",
    "Amman",
    "Amsterdam",
    "Ankara",
    "Antananarivo",
    "Apia",
    "Ashgabat",
    "Asmara",
    "Astana",
    "Asunción",
    "Athens",
    "Baghdad",
    "Baku",
    "Bamako",
    "Bangkok",
    "Bangui",
    "Banjul",
    "Basseterre",
    "Beijing",
    "Beirut",
    "Belgrade",
    "Belmopan",
    "Berlin",
    "Bern",
    "Bishkek",
    "Bissau",
    "Bogotá",
    "Brasília",
    "Bratislava",
    "Brazzaville",
    "Bridgetown",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Buenos Aires",
    "Bujumbura",
    "Cairo",
    "Canberra",
    "Cape Town",
    "Caracas",
    "Castries",
    "Chisinau",
    "Conakry",
    "Copenhagen",
    "Cotonou",
    "Dakar",
    "Damascus",
    "Dhaka",
    "Dili",
    "Djibouti",
    "Dodoma",
    "Doha",
    "Dublin",
    "Dushanbe",
    "Delhi",
    "Freetown",
    "Funafuti",
    "Gabarone",
    "Georgetown",
    "Guatemala City",
    "Hague",
    "Hanoi",
    "Harare",
    "Havana",
    "Helsinki",
    "Honiara",
    "Hong Kong",
    "Islamabad",
    "Jakarta",
    "Jerusalem",
    "Kabul",
    "Kampala",
    "Kathmandu",
    "Khartoum",
    "Kyiv",
    "Kigali",
    "Kingston",
    "Kingstown",
    "Kinshasa",
    "Kuala Lumpur",
    "Kuwait City",
    "La Paz",
    "Liberville",
    "Lilongwe",
    "Lima",
    "Lisbon",
    "Ljubljana",
    "Lobamba",
    "Lomé",
    "London",
    "Luanda",
    "Lusaka",
    "Luxembourg",
    "Madrid",
    "Majuro",
    "Malé",
    "Managua",
    "Manama",
    "Manila",
    "Maputo",
    "Maseru",
    "Mbabane",
    "Melekeok",
    "Mexico City",
    "Minsk",
    "Mogadishu",
    "Monaco",
    "Monrovia",
    "Montevideo",
    "Moroni",
    "Moscow",
    "Muscat",
    "Nairobi",
    "Nassau",
    "Naypyidaw",
    "N'Djamena",
    "New Delhi",
    "Niamey",
    "Nicosia",
    "Nouakchott",
    "Nuku'alofa",
    "Nuuk",
    "Oslo",
    "Ottawa",
    "Ouagadougou",
    "Palikir",
    "Panama City",
    "Paramaribo",
    "Paris",
    "Phnom Penh",
    "Podgorica",
    "Prague",
    "Praia",
    "Pretoria",
    "Pyongyang",
    "Quito",
    "Rabat",
    "Ramallah",
    "Reykjavík",
    "Riga",
    "Riyadh",
    "Rome",
    "Roseau",
    "San José",
    "San Marino",
    "San Salvador",
    "Sanaá",
    "Santiago",
    "Santo Domingo",
    "Sao Tomé",
    "Sarajevo",
    "Seoul",
    "Singapore",
    "Skopje",
    "Sofia",
    "South Tarawa",
    "St. George's",
    "St. John's",
    "Stockholm",
    "Sucre",
    "Suva",
    "Taipei",
    "Tallinn",
    "Tashkent",
    "Tbilisi",
    "Tegucigalpa",
    "Teheran",
    "Thimphu",
    "Tirana",
    "Tokyo",
    "Tripoli",
    "Tunis",
    "Ulaanbaatar",
    "Vaduz",
    "Valletta",
    "Victoria",
    "Vienna",
    "Vientiane",
    "Vilnius",
    "Warsaw",
    "Washington",
    "Wellington",
    "Windhoek",
    "Yamoussoukro",
    "Yaoundé",
    "Yerevan",
    "Zagreb",
    "Zielona Góra",
    "Poznań",
    "Wrocław",
    "Gdańsk",
    "Szczecin",
    "Łódź",
    "Białystok",
    "Toruń",
    "St. Petersburg",
    "Turku",
    "Örebro",
    "Chengdu",
    "Wuppertal",
    "Frankfurt",
    "Düsseldorf",
    "Essen",
    "Duisburg",
    "Magdeburg",
    "Bonn",
    "Brno",
    "Tours",
    "Bordeaux",
    "Nice",
    "Lyon",
    "Stara Zagora",
    "Milan",
    "Bologna",
    "Sydney",
    "Venice",
    "New York",
    "Barcelona",
    "Zaragoza",
    "Valencia",
    "Seville",
    "Graz",
    "Munich",
    "Birmingham",
    "Naples",
    "Cologne",
    "Turin",
    "Marseille",
    "Leeds",
    "Kraków",
    "Palermo",
    "Genoa",
    "Stuttgart",
    "Dortmund",
    "Rotterdam",
    "Glasgow",
    "Málaga",
    "Bremen",
    "Sheffield",
    "Antwerp",
    "Plovdiv",
    "Thessaloniki",
    "Kaunas",
    "Lublin",
    "Varna",
    "Ostrava",
    "Iaşi",
    "Katowice",
    "Cluj-Napoca",
    "Timişoara",
    "Constanţa",
    "Pskov",
    "Vitebsk",
    "Arkhangelsk",
    "Novosibirsk",
    "Samara",
    "Omsk",
    "Chelyabinsk",
    "Ufa",
    "Volgograd",
    "Perm",
    "Kharkiv",
    "Odessa",
    "Donetsk",
    "Dnipropetrovsk",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "Dallas",
    "Detroit",
    "Indianapolis",
    "San Francisco",
    "Atlanta",
    "Austin",
    "Vermont",
    "Toronto",
    "Montreal",
    "Vancouver",
    "Gdynia",
    "Edmonton"
  ]

  @doc "All city names, in the original's order."
  @spec all() :: [String.t()]
  def all, do: @names
end
