import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :hex_empire, HexEmpireWeb.Endpoint,
  # Deliberately bound to all interfaces so the dev server is reachable from
  # other machines on the LAN (playing from a phone). Use {127, 0, 0, 1} to
  # restrict access to this machine only.
  http: [ip: {0, 0, 0, 0}],
  # Public hostname (the `ferri` tunnel forwards it to this dev server) —
  # makes generated absolute URLs point at the shareable address.
  url: [host: "sixteen-housels.ferri.run", scheme: "https", port: 443],
  # Accessed via the tunnel hostname, LAN IPs, Tailscale, and localhost —
  # origin checking stays off in dev to allow all of them.
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "st427w5fFm8JvVflcnJavrrc3M3LyOflDK3VdbdkIqgHtHRmzXFWANJ8Ge9+Z48s",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:hex_empire, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:hex_empire, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :hex_empire, HexEmpireWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/hex_empire_web/router\.ex$"E,
      ~r"lib/hex_empire_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Dev-only VAPID keys for Web Push (prod uses VAPID_* env vars; see runtime.exs)
config :ex_nudge,
  vapid_subject: "mailto:christophe.detroyer@gmail.com",
  vapid_public_key:
    "BOhtlOYMokwHTJwr0zWNo5hBhnh3Hr9XJyYAZ1Jauf0VD9X1wwdniPSFU-0SoI2O-cFcCIZLs3EYQEDFFMvJR5o",
  vapid_private_key: "ne081_iO93ZStrbmgs6khkipjplsT_gZeLUiqVay1D8"
